### ISSUE TITLE
Deployment de imagens docker a partir do travis

### ISSUE THREAD

**Issue by edusantana** [abntex/limarka#111]
**Comportamento esperado**: as novas releases deverão ser geradas a partir do travis.

Ver: 
- https://docs.travis-ci.com/user/deployment/rubygems/

Publicar imagem docker:

- https://github.com/travis-ci/build-stages-demo/tree/share-docker-image/

**Comment by edusantana** [comment]
Por enquanto não está funcionando. Não sei porque.

**Comment by edusantana** [comment]
Ajuda com esse issue seria bastante apreciada.

**Comment by edusantana** [comment]
```
deploy:
  - provider: rubygems
    api_key: $RUBYGEMS_API_KEY
    on:
      tags: true
```
