### ISSUE TITLE
Possibilitar alterar as configurações através de páginas HTML

### ISSUE THREAD

**Issue by edusantana** [abntex/limarka#166]
**Comportamento esperado**:

O ideal seria possibilitar realizar as configurações através de HTML que permite a construção de formulários que possibilitam uma experiência de interações melhores.

> Atualmente é possível ler as configurações apenas de YAML ou PDF.

**Comment by edusantana** [comment]
@cauachagas enviou a seguinte imagem sobre essa idéia:

![captura-de-tela_2018-10-21_14-57-54](https://user-images.githubusercontent.com/3603111/47288386-4c015300-d5cc-11e8-9637-61d15b619333.png)

**Comment by cauachagas** [comment]
Este primeiro arquivo compactado contém só o formulário html 

[configuracao.html.zip](https://github.com/abntex/limarka/files/2502047/configuracao.html.zip)

O segundo, contém o formulário e a pasta arquivos necessários. Quando o formulário html é salvo (Ctrl + S), cria uma pasta com esses arquivos (são as figuras contidas em "imagens/configuracao/"). Deve haver um jeito de colocar "imagens/configuracao" como diretório de imagens, pra evitar esse comportamento. Infelizmente, não tenho conhecimento em html. 

[configuracao-html.zip](https://github.com/abntex/limarka/files/2502067/configuracao-html.zip)

Todos os campos, coloquei com 
```html
<form></form>
``` 
, porém só as estruturas 
```html
<select></select>
```
, que geram lista com opções (como tipo de trabalho e adicionar/desativar anexos), conseguem ser extraídos com o pacote *nokogiri* do ruby. Abaixo um exemplo de como podem ser extraídos as informações com *doc.search('form')[n].text*, onde **n** significa a ordem apresentada das informações pedidas no arquivo configuracao.pdf

```ruby

require 'nokogiri'

doc = Nokogiri::HTML(open('configuracao.html'), nil, "UTF-8")

nivel_educacao = doc.search('form')[0].text # form. lista

projeto_combo = doc.search('form')[1].text # form. lista

instituicao = doc.search('form')[2].text # form. area de texto; não consegue ser extraído

```

**Comment by edusantana** [comment]
Se eu fosse fazer isso daí, provavelmente eu iria fazer uma [aplicação sinatra](http://sinatrarb.com/intro.html).

Como você faz para persistir os dados do formulário?

**Comment by edusantana** [comment]
@cauachagas Entendi o funcionamento proposto, é similar ao PDF. Persistir os dados dentro do arquivo HTML e salvar como outro arquivo HTML.

Nessa sua abordagem iria ler os dados HTML e exportaria para o formato YAML, que é lido pelo limarka.

<hr>
Eu realmente estava pensando em uma aplicação web que edita os parâmetros, com múltiplas páginas, uma para cada seção. Com recursos para validar os dados inseridos etc.

Eu pensei no [sinatra](http://sinatrarb.com/intro.html) porque ele possibilita tudo isso e não é um monstro como [rails](https://rubyonrails.org/).

Independente do que desejar fazer, recomendo a criação de um projeto separado, criado em https://github.com/limarka

Da mesma forma que do [pandoc_abnt](https://github.com/limarka/pandoc_abnt), que é utilizado pelo limarka.

Se precisar de ajuda estou a disposição.

**Comment by cauachagas** [comment]
Não tenho conhecimento de html. Apenas usei o Google. Crei esse formulário usando pandoc. Basicamente odt --> md --> html. Só fiz editar o arquivo html gerado com atributos do tipo formulário.

 Em [154](https://github.com/abntex/limarka/issues/154), fala sobre alternativas ao LaTeX (html para pdf, no caso). Então, pensei em criar um formulário html, caso o limarka comece a usar html.

Lendo um pouco sobre extrair informações de formulários html, vi sobre incorporar o Ruby (um tal de erb) ou até usar outra linguagem, como o python, pra mexer em HTML. Enfim... Vou tentar explorar sobre o assunto por esses dias.

**Comment by edusantana** [comment]
> Em #154, fala sobre alternativas ao LaTeX (html para pdf, no caso). Então, pensei em criar um formulário html, caso o limarka comece a usar html.

Isso é outra coisa. Atualmente podemos realizar as configurações através de código YAML ou PDF, e talvez em HTML no futuro.

Independente da forma como as configurações são lidas, os passos como o limarka processa as informações necessita do LaTeX e do abntex2 (quem possibilita a compatibilidade com o ABNT).

Torna-se independente do LaTeX significa implementar tudo o que o abntex2 (verificar compatibilidade com as normas da ABNT) através de estilos CSS para impressão.

Da última vez que investiguei isso não era possível ainda. Basicamente é o seguinte:

> As vezes na internet quando clicamos para imprimir uma página a impressão remove alguns elementos da página desnecessários, e torna o documento impresso melhor. 
> Implementar #154 significa criar a possibilidade de imprimir uma página HTML de acordo com as normas da ABNT: cabeçalhos, numeração de página, numeração de capítulos e seções, espaçamentos, tamanho de fontes, etc.

**Comment by sergiopvilar** [comment]
Porque não usar o HTML pra gerar um código YAML que pode ser criado pelo próprio usuário?

Por ex, o usuário usa o HTML pra fazer todas configurações e ao final tem um YAML pronto.

**Comment by cauachagas** [comment]
@sergiopvilar , tens experiência nesse tópico? Eu criei o repositório [limarka-sinatra](https://github.com/limarka/limarka-sinatra) com esse objetivo, mas não tenho muita afinidade com o assunto. Até onde lembro, estava funcional. PRs serão apreciados.

A dificuldade que tive foi em recuperar os valores de listas (drop-down) a partir de um `.yaml`. Por exemplo, em *Nível de Educação do Trabalho*, eu seleciono "Mestrado". Ao submeter o formulário, criará um `.yaml` válido para o Limarka. Supondo que foi finalizado http://localhost:4567, caso o usuário queira trocar alguma informação, ao abrir o formulário novamente, em *Nível de Educação do Trabalho* estará o valor padrão, que é "Graduação" e não "Mestrado", como havia primeiramente submetido.

Isso causa um efeito dominó, pois há outras informações que são em drop-down. Por esse motivo, não criei um formulário completo.

**Comment by sergiopvilar** [comment]
@cauachagas tenho experiência sim! Estou em semana de provas e posso contribuir com isso a partir do dia 19, vou ver como está o estado atual e o que pode ser feito.

**Comment by sergiopvilar** [comment]
@cauachagas acabei arrumando um tempo e criei o MR (https://github.com/limarka/limarka-sinatra/pull/7), só fiquei na dúvida dos valores possíveis pra a chave `tipo`.

**Comment by cauachagas** [comment]
@sergiopvilar , obrigado. Quanto aos valores. Acho que não existe a chave `tipo` e sim `tipo_do_trabalho`. Não sei como não havia notado. 

Retirado da versão mais recente do limarka, tem esse arquivo `.yaml`:

```yaml
---
instituicao: Universidade/Faculdade do Brasil
author: Nome do autor
title: Título do trabalho
local: Cidade - UF
date: '2019'
capa_pdf_caminho: ''
titulacao: Minha-titulação
curso: Meu-curso
programa: Programa de Pós-Graduação em XXX
area_de_concentracao: Computação
linha_de_pesquisa: ''
coorientador: ''
orientador: Nome-do-Orientador
referencias_caminho: referencias.bib
proposito: ''
resumo: ''
palavras_chave: ''
keywords: ''
abstract_texto: ''
resumen: ''
palabras_clave: ''
resume: ''
mots_cles: ''
siglas:
- s: ABNT
  d: Associação Brasileira de Normas Técnicas
simbolos: 
dedicatoria: ''
agradecimentos: ''
epigrafe: ''
avaliador2: Nome-do-Prof-Convidado2
aprovacao_dia: '1'
avaliador1: Nome-do-Prof-Convidado1
avaliador3: ''
graduacao: true
especializacao: false
mestrado: false
doutorado: false
tipo_do_trabalho: Monografia
incluir_ficha_catalografica: false
folha_de_aprovacao: false
projeto: true
apendices: false
anexos: false
errata: false
referencias_sistema: alf
lista_ilustracoes: false
lista_quadros: yes
lista_tabelas: yes
---
```
